# Generated by Django 5.1.6 on 2025-04-29 20:18

from django.db import migrations, models

import arts.models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(upload_to=arts.models.art_image_path, verbose_name='Изображение'),
        ),
    ]
