# Generated by Django 5.1.6 on 2025-05-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', verbose_name='Ссылочное название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.recipecategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', verbose_name='Ссылочное название')),
                ('categories', models.ManyToManyField(blank=True, to='categories.recipecategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Группа категорий',
                'verbose_name_plural': 'Группы категорий',
            },
        ),
    ]
