# Generated by Django 5.1.6 on 2025-03-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categorygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', verbose_name='Ссылочное название'),
        ),
    ]
