# Generated by Django 5.1.6 on 2025-05-12 09:39

import additions.models
import additions.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('code', models.UUIDField(default=uuid.uuid4, verbose_name='Код подтверждения')),
                ('expiration', models.DateTimeField(default=additions.models.default_expiration, verbose_name='Срок действия')),
                ('accepted', models.BooleanField(default=False, verbose_name='Код подтверждён')),
            ],
            options={
                'verbose_name': 'Код подтверждения',
                'verbose_name_plural': 'Коды подтверждения',
            },
        ),
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Страница', max_length=200, verbose_name='Название для админки')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='URL страницы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок (title)')),
                ('description', models.TextField(verbose_name='Описание (description)')),
                ('og_title', models.CharField(blank=True, max_length=200, verbose_name='OpenGraph Title')),
                ('og_description', models.TextField(blank=True, verbose_name='OpenGraph Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to=additions.models.meta_og_image_path, verbose_name='OpenGraph Image URL')),
            ],
            options={
                'verbose_name': 'Мета-тег',
                'verbose_name_plural': 'Мета-теги',
            },
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(blank=True, null=True, validators=[additions.validators.validate_telegram_url], verbose_name='Телеграм')),
                ('vk', models.URLField(blank=True, null=True, validators=[additions.validators.validate_vk_url], verbose_name='ВКонтакте')),
                ('pinterest', models.URLField(blank=True, null=True, validators=[additions.validators.validate_pinterest_url], verbose_name='Pinterest')),
                ('youtube', models.URLField(blank=True, null=True, validators=[additions.validators.validate_youtube_url], verbose_name='Youtube')),
                ('rutube', models.URLField(blank=True, null=True, validators=[additions.validators.validate_rutube_url], verbose_name='Rutube')),
            ],
            options={
                'verbose_name': 'Соцсеть',
                'verbose_name_plural': 'Соцсети',
            },
        ),
    ]
