# Generated by Django 5.1.6 on 2025-03-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='URL страницы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок (title)')),
                ('description', models.TextField(verbose_name='Описание (description)')),
                ('og_title', models.CharField(blank=True, max_length=200, verbose_name='OpenGraph Title')),
                ('og_description', models.TextField(blank=True, verbose_name='OpenGraph Description')),
                ('og_image', models.ImageField(upload_to='meta_og_images/', verbose_name='OpenGraph Image URL')),
            ],
            options={
                'verbose_name': 'Мета-тег',
                'verbose_name_plural': 'Мета-теги',
            },
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Телеграм')),
                ('vk', models.URLField(blank=True, null=True, verbose_name='ВКонтакте')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
                ('pinterest', models.URLField(blank=True, null=True, verbose_name='Pinterest')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('rutube', models.URLField(blank=True, null=True, verbose_name='Rutube')),
            ],
            options={
                'verbose_name': 'Соцсеть',
                'verbose_name_plural': 'Соцсети',
            },
        ),
    ]
