# Generated by Django 5.1.6 on 2025-04-29 20:18

from django.db import migrations, models

import additions.models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='og_image',
            field=models.ImageField(upload_to=additions.models.meta_og_image_path, verbose_name='OpenGraph Image URL'),
        ),
    ]
