# Generated by Django 5.1.6 on 2025-05-05 10:47

import additions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0002_alter_metatag_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socials',
            name='pinterest',
            field=models.URLField(blank=True, null=True, validators=[additions.validators.validate_pinterest_url], verbose_name='Pinterest'),
        ),
        migrations.AlterField(
            model_name='socials',
            name='rutube',
            field=models.URLField(blank=True, null=True, validators=[additions.validators.validate_rutube_url], verbose_name='Rutube'),
        ),
        migrations.AlterField(
            model_name='socials',
            name='telegram',
            field=models.URLField(blank=True, null=True, validators=[additions.validators.validate_telegram_url], verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='socials',
            name='vk',
            field=models.URLField(blank=True, null=True, validators=[additions.validators.validate_vk_url], verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='socials',
            name='youtube',
            field=models.URLField(blank=True, null=True, validators=[additions.validators.validate_youtube_url], verbose_name='Youtube'),
        ),
    ]
