# Generated by Django 5.1.6 on 2025-05-08 08:49

import additions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0003_alter_socials_pinterest_alter_socials_rutube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatag',
            name='display_name',
            field=models.CharField(default='Страница', max_length=200, verbose_name='Название для админки'),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to=additions.models.meta_og_image_path, verbose_name='OpenGraph Image URL'),
        ),
    ]
