# Generated by Django 5.1.6 on 2025-03-07 08:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылочное название')),
                ('preview', models.ImageField(upload_to='news_previews/', verbose_name='Превью')),
                ('description_card', models.CharField(max_length=64, verbose_name='Описание для карточки')),
                ('content_start', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент 1 часть')),
                ('content_middle', models.TextField(blank=True, default='', null=True, verbose_name='Вставка')),
                ('content_end', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Контент 2 часть')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Опубликовано'), (2, 'Не опубликовано'), (3, 'Черновик'), (4, 'На проверке')], verbose_name='Статус')),
                ('visibility', models.PositiveSmallIntegerField(choices=[(1, 'Все'), (2, 'Только в профиле'), (3, 'Только подписчики'), (4, 'Только я')], verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['title'],
            },
        ),
    ]
