# Generated by Django 5.1.6 on 2025-04-13 08:09

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', verbose_name='Ссылочное название')),
                ('preview', models.ImageField(upload_to='news_previews/', verbose_name='Превью')),
                ('description_card', models.CharField(max_length=64, verbose_name='Описание для карточки')),
                ('content_start', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент 1 часть')),
                ('content_middle', models.TextField(blank=True, default='', null=True, verbose_name='Вставка')),
                ('content_end', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Контент 2 часть')),
                ('headings', models.JSONField(blank=True, default=list, null=True, verbose_name='Содержание')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Опубликовано'), (2, 'Не опубликовано'), (3, 'Черновик'), (4, 'На проверке')], verbose_name='Статус')),
                ('visibility', models.PositiveSmallIntegerField(choices=[(1, 'Все'), (2, 'Только в профиле'), (3, 'Только подписчики'), (4, 'Только я')], verbose_name='Видимость')),
                ('popularity', models.PositiveSmallIntegerField(default=0, verbose_name='Популярность')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=1024, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comments_images/', verbose_name='Изображение')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('likes', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во лайков')),
                ('dislikes', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во дизлайков')),
            ],
            options={
                'verbose_name': 'Комментарий к статье',
                'verbose_name_plural': 'Комментарии к статьям',
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='NewsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Оценка статьи',
                'verbose_name_plural': 'Оценки статей',
            },
        ),
    ]
