# Generated by Django 5.1.6 on 2025-04-29 20:18

from django.db import migrations, models

import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(upload_to=news.models.news_preview_image_path, verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.news_comments_image_path, verbose_name='Изображение'),
        ),
    ]
