# Generated by Django 5.1.6 on 2025-05-04 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_preview_alter_newscomment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обновления статуса'),
        ),
    ]
