# Generated by Django 5.1.6 on 2025-03-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_rating'),
        ('users', '0004_remove_review_content_type_remove_review_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reviews',
            field=models.ManyToManyField(to='users.review', verbose_name='Оценки'),
        ),
    ]
