# Generated by Django 5.1.6 on 2025-03-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='popularity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Популярность'),
        ),
    ]
