# Generated by Django 5.1.6 on 2025-03-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='headings',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Содержание'),
        ),
    ]
