# Generated by Django 5.1.6 on 2025-04-20 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='previews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipepreview', verbose_name='Превью'),
        ),
    ]
