# Generated by Django 5.1.6 on 2025-03-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', verbose_name='Ссылочное название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', verbose_name='Ссылочное название'),
        ),
    ]
