# Generated by Django 5.1.6 on 2025-05-15 17:55

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=recipes.models.ingredient_image_path, verbose_name='Иконка'),
        ),
    ]
