# Generated by Django 5.1.6 on 2025-04-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_previews'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='can_exclude',
            field=models.BooleanField(default=False, verbose_name='Можно убрать'),
        ),
    ]
