# Generated by Django 5.1.6 on 2025-04-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeingredient_can_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description_card',
            field=models.CharField(max_length=64, null=True, verbose_name='Описание для карточки'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description_inner',
            field=models.TextField(max_length=1024, null=True, verbose_name='Описание внутри'),
        ),
    ]
