# Generated by Django 5.1.6 on 2025-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_reviews'),
        ('users', '0004_remove_review_content_type_remove_review_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='users.review', verbose_name='Оценки'),
        ),
    ]
