# Generated by Django 5.1.6 on 2025-04-26 14:32

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_description_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['sort_order'], 'verbose_name': 'Шаг в рецепте', 'verbose_name_plural': 'Шаги в рецептах'},
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='image',
            field=models.ImageField(upload_to=recipes.models.recipe_step_image_path, verbose_name='Изображение'),
        ),
    ]
