# Generated by Django 5.1.6 on 2025-04-29 19:57

from django.db import migrations, models

import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipestep_options_alter_recipestep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='icon',
            field=models.FileField(upload_to=recipes.models.ingredient_image_path, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.recipe_comments_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipepreview',
            name='preview_1',
            field=models.ImageField(upload_to=recipes.models.recipe_preview_image_path, verbose_name='Превью 1'),
        ),
        migrations.AlterField(
            model_name='recipepreview',
            name='preview_2',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.recipe_preview_image_path, verbose_name='Превью 2'),
        ),
        migrations.AlterField(
            model_name='recipepreview',
            name='preview_3',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.recipe_preview_image_path, verbose_name='Превью 3'),
        ),
    ]
