# Generated by Django 5.1.6 on 2025-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredient_icon_alter_recipecomment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='popularity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Популярность'),
        ),
    ]
