# Generated by Django 5.1.6 on 2025-05-04 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_ingredient_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обновления статуса'),
        ),
    ]
