# Generated by Django 5.1.6 on 2025-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_status_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cache_version',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Версия кэша'),
        ),
    ]
