# Generated by Django 5.1.6 on 2025-03-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='weight_per_unit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Вес 1 штуки'),
        ),
    ]
