# Generated by Django 5.1.6 on 2025-03-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_ingredient_weight_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='icon',
            field=models.FileField(upload_to='ingredient_icons/', verbose_name='Иконка'),
        ),
    ]
