# Generated by Django 5.1.6 on 2025-03-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_ingredient_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='popularity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Популярность'),
        ),
    ]
