# Generated by Django 5.1.6 on 2025-04-13 08:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additions', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория достижения',
                'verbose_name_plural': 'Категории достижений',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Название')),
                ('hash', models.CharField(max_length=64, verbose_name='Цвет фона')),
                ('text_hash', models.CharField(default='#000000', max_length=64, verbose_name='Цвет текста')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Поле сортировки')),
            ],
            options={
                'verbose_name': 'Цвет фона',
                'verbose_name_plural': 'Цвета фона',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GeneralAchievementCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Общее условие')),
            ],
            options={
                'verbose_name': 'Условие получения достижения',
                'verbose_name_plural': 'Условия получения достижений',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Название')),
                ('icon', models.FileField(upload_to='achiv_icons/', verbose_name='Иконка')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Серебро'), (2, 'Золото'), (3, 'Рубин')], verbose_name='Уровень')),
                ('condition_self', models.CharField(max_length=128, verbose_name='Конкретное условие')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categoryachievement', verbose_name='Категория')),
                ('condition_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.generalachievementcondition', verbose_name='Общее условие')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, default='Вкусная печенька 🍪', max_length=32, null=True, verbose_name='Отображаемое имя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users_avatars/', verbose_name='Аватарка')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('description_profile', models.TextField(blank=True, default='Добро пожаловать в мой профиль! Я увлечен(а) кулинарией и верю, что вкусная еда делает жизнь ярче. Надеюсь, мои рецепты и советы будут полезны для вас!', max_length=512, null=True, verbose_name='Описание профиля')),
                ('description_recipe', models.TextField(blank=True, default='Привет! Я обожаю готовить и экспериментировать на кухне. Для меня кулинария — это не просто процесс, а настоящее искусство. Буду рад(а) делиться с вами своими любимыми рецептами и советами!', max_length=512, null=True, verbose_name='Описание для рецепта')),
                ('description_news', models.TextField(blank=True, default='Добро пожаловать в мой кулинарный блог! Здесь я делюсь интересными фактами, советами и историями о еде. Надеюсь, мои статьи помогут вам открыть для себя что-то новое и вдохновят на эксперименты!', max_length=512, null=True, verbose_name='Описание для статьи')),
                ('disliked_news_comments', models.ManyToManyField(blank=True, related_name='disliked_news_comments_set', to='news.newscomment', verbose_name='Дизлайкнутые комментарии статей')),
                ('disliked_recipe_comments', models.ManyToManyField(blank=True, related_name='disliked_recipe_comments_set', to='recipes.recipecomment', verbose_name='Дизлайкнутые комментарии рецептов')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('liked_news_comments', models.ManyToManyField(blank=True, related_name='liked_news_comments_set', to='news.newscomment', verbose_name='Лайкнутые комментарии статьи')),
                ('liked_recipe_comments', models.ManyToManyField(blank=True, related_name='liked_recipe_comments_set', to='recipes.recipecomment', verbose_name='Лайкнутые комментарии рецепта')),
                ('liked_recipes', models.ManyToManyField(blank=True, to='recipes.recipe', verbose_name='Понравившиеся рецепты')),
                ('socials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='additions.socials', verbose_name='Соцсети')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribers_set', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscriptions_set', to=settings.AUTH_USER_MODEL, verbose_name='Подписки')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('achivs', models.ManyToManyField(blank=True, related_name='achivs_set', to='users.achievement', verbose_name='Полученные достижения')),
                ('choosed_achiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choosed_achiv_set', to='users.achievement', verbose_name='Выбранное достижение')),
                ('background_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.color', verbose_name='Цвет фона')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
