# Generated by Django 5.1.6 on 2025-03-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', verbose_name='Ссылочное название'),
        ),
    ]
