# Generated by Django 5.1.6 on 2025-04-29 20:18

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.FileField(upload_to=users.models.achiv_icon_image_path, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.users_avatar_image_path, verbose_name='Аватарка'),
        ),
    ]
