# Generated by Django 5.1.6 on 2025-03-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='review',
            name='object_id',
        ),
    ]
