# Generated by Django 5.1.6 on 2025-03-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comment_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_comments_id',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Дизлайкнутые комментарии'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_comments_id',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Лайкнутые комментарии'),
        ),
    ]
