# Generated by Django 5.1.6 on 2025-03-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_disliked_comments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achivs',
            field=models.ManyToManyField(blank=True, to='users.achievement', verbose_name='Полученные достижения'),
        ),
    ]
