# Generated by Django 5.1.6 on 2025-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description_news',
            field=models.TextField(blank=True, default='Добро пожаловать в мой кулинарный блог! Здесь я делюсь интересными фактами, советами и историями о еде. Надеюсь, мои статьи помогут вам открыть для себя что-то новое и вдохновят на эксперименты!', max_length=512, null=True, verbose_name='Описание для статьи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description_profile',
            field=models.TextField(blank=True, default='Добро пожаловать в мой профиль! Я увлечен(а) кулинарией и верю, что вкусная еда делает жизнь ярче. Надеюсь, мои рецепты и советы будут полезны для вас!', max_length=512, null=True, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description_recipe',
            field=models.TextField(blank=True, default='Привет! Я обожаю готовить и экспериментировать на кухне. Для меня кулинария — это не просто процесс, а настоящее искусство. Буду рад(а) делиться с вами своими любимыми рецептами и советами!', max_length=512, null=True, verbose_name='Описание для рецепта'),
        ),
    ]
