# Generated by Django 5.1.6 on 2025-03-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_description_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='Ореховый брауни 🥜', max_length=32, null=True, verbose_name='Отображаемое имя'),
        ),
    ]
