# Generated by Django 5.1.6 on 2025-03-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.FileField(upload_to='achiv_icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='Клубничный торт', max_length=32, null=True, verbose_name='Отображаемое имя'),
        ),
    ]
