# Generated by Django 5.1.6 on 2025-03-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='Сливочный пудинг 🍮', max_length=32, null=True, verbose_name='Отображаемое имя'),
        ),
    ]
