# Generated by Django 5.1.6 on 2025-03-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='Вкусная печенька 🍪', max_length=32, null=True, verbose_name='Отображаемое имя'),
        ),
    ]
